# Generated by Django 5.2.9 on 2026-01-05 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sent', 'sent'), ('opened', 'opened'), ('clicked', 'clicked'), ('replied', 'replied')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contact')),
                ('scheduled_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generation.scheduledmessage')),
            ],
        ),
    ]
