# Generated by Django 5.2.9 on 2026-01-05 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('playbooks', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('sent', 'sent'), ('demo_blocked', 'demo_blocked')], default='scheduled', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contact')),
                ('playbook_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playbooks.playbookstep')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_prompt', models.TextField()),
                ('output_text', models.TextField()),
                ('diff_from_previous', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='playbooks.promptversion')),
                ('scheduled_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='generation.scheduledmessage')),
            ],
        ),
    ]
